/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pak;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Niki1oo1 //https://github.com/Niki1oo1/Koch-snowflake
 */
public class Title extends javax.swing.JFrame {
    
    public Title() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        btnDraw = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlMain.setPreferredSize(new java.awt.Dimension(930, 615));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        txt1.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        txt1.setText("Iterations:");

        btnDraw.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        btnDraw.setText("Draw");
        btnDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnClr.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        btnClr.setText("Clear");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });

        btnTest.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        btnTest.setText("Example");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtInput)
                    .addComponent(btnDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(txt1)
                .addGap(18, 18, 18)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDraw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawActionPerformed
        Pattern pat = Pattern.compile("[^0123456789]", Pattern.CASE_INSENSITIVE);
        Matcher match = pat.matcher(txtInput.getText());
        if (match.find()) {
            JOptionPane.showMessageDialog(rootPane, "Error!");
            txtInput.setText(null);
        } else {
            int n = Integer.parseInt(txtInput.getText());
            if (n <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Error!");
                txtInput.setText(null);
            } else {

                Graphics g = pnlMain.getGraphics();

                int xa = 240; //x(A)
                int xb = pnlMain.getWidth() - 240; //x(B)
                int xc = pnlMain.getWidth() / 2; //x(C)

                int ya = pnlMain.getHeight() - 200; //y(A)
                int yb = pnlMain.getHeight() - 200; //y(B)
                int yc = (int) (pnlMain.getHeight() - 200 - (pnlMain.getWidth() - 480) * Math.sqrt(3.0) / 2); //y(C)

                Point2D t[] = new Point2D.Double[3];

                for (int i = 0; i < t.length; i++) {
                    t[i] = new Point2D.Double();
                }

                t[0].setLocation(xa, ya);
                t[1].setLocation(xb, yb);
                t[2].setLocation(xc, yc);

                g.setColor(Color.GREEN);
                Functions.drawPoly(g, t);

                g.setColor(Color.BLACK);
                Functions.drawKoch(g, t, n);

            }
        }
    }//GEN-LAST:event_btnDrawActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        try {
            Robot r = new Robot();

            Point p0 = pnlMain.getLocationOnScreen();
            Point p1 = new Point(pnlMain.getWidth(), pnlMain.getHeight());
            Rectangle screenRect = new Rectangle((int) p0.getX(), (int) p0.getY(), (int) p1.getX(), (int) p1.getY());

            BufferedImage img = r.createScreenCapture(screenRect);

            File image = new File("export.png");
            ImageIO.write(img, "png", image);
        } catch (AWTException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
        pnlMain.repaint();
    }//GEN-LAST:event_btnClrActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        int n = 5;
        txtInput.setText("" + n);

        Graphics g = pnlMain.getGraphics();

        int xa = 240; //x(A)
        int xb = pnlMain.getWidth() - 240; //x(B)
        int xc = pnlMain.getWidth() / 2; //x(C)

        int ya = pnlMain.getHeight() - 200; //y(A)
        int yb = pnlMain.getHeight() - 200; //y(B)
        int yc = (int) (pnlMain.getHeight() - 200 - (pnlMain.getWidth() - 480) * Math.sqrt(3.0) / 2); //y(C)

        Point2D t[] = new Point2D.Double[3];

        for (int i = 0; i < t.length; i++) {
            t[i] = new Point2D.Double();
        }

        t[0].setLocation(xa, ya);
        t[1].setLocation(xb, yb);
        t[2].setLocation(xc, yc);

        g.setColor(Color.GREEN);
        Functions.drawPoly(g, t);

        g.setColor(Color.BLACK);
        Functions.drawKoch(g, t, n);
    }//GEN-LAST:event_btnTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Title.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Title.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Title.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Title.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Title().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnDraw;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnTest;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JLabel txt1;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
